name: Pipeline DevSecOps - Projet 5DVSCOPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      # Étape de Linting YAML (Partie 2 du sujet)
      - name: Yaml Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_data: "{extends: default, rules: {line-length: disable}}"

      # Étape de Build Docker (Partie 2 du sujet)
      - name: Build de l'image Docker
        run: docker build -t devsecops-project:latest .
